### ISSUE TITLE
New Python handler is here

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/mkdocstrings#364]
Hello everyone!

I've been working on a new Python handler. This issue serves as a public TODO list for what is needed before getting it out of the "experimental" state.

The new handler is [mkdocstrings/python](https://github.com/mkdocstrings/python), and the old one has been extracted into [mkdocstrings/python-legacy](https://github.com/mkdocstrings/python-legacy). The new data collector, [mkdocstrings/griffe](https://github.com/mkdocstrings/griffe), is an improved version of [mkdocstrings/pytkdocs](https://github.com/mkdocstrings/pytkdocs). It's able to both visit (AST) and inspect (exec + introspection) objects, and has an overall better design.

### Phase 1

- [x] Finish implementing support for namespace packages in griffe
- [x] Publish a new griffe release
- [x] Fix docstrings admonitions rendering in mkdocstrings/python
- [x] Use the new `mkdocstrings_handlers` namespace in mkdocstrings/python
- [x] Publish a new mkdocstrings/python release
- [x] Open mkdocstrings PR to allow it to load handlers from the `mkdocstrings_handlers` namespace (with backward-compatibility and deprecation warnings) #356 and #367
- [x] Update PR #356 with the `python` experimental extra actually installing mkdocstrings-python
- [x] Update docs about the new handler: things that can possibly stop working (dynamic objects, custom templates?), deprecations, user warnings, how to ignore them, etc. #371 
- [x] Add user warning (specify extra) when using mkdocstrings/python-legacy
- [x] Publish new legacy handler release
- [x] Merge all mkdocstrings PRs
- [x] Publish a new mkdocstrings release 
- [x] At this point users can start testing the new handler by depending on `mkdocstrings[python]`
- [x] Add back usage docs on the legacy handler docs
- [x] Enjoy a round of bugtracker cleaning :drooling_face: 

---

### Phase 2

- [x] Stop depending on the legacy handler in mkdocstrings
- [x] Remove user warning when using mkdocstrings/python-legacy (since by now the extra is mandatory)
- [x] Use the new mkdocstrings_handlers namespace in mkdocstrings/python-legacy as well
- [x] Refactor mkdocstrings to get rid of the `BaseCollector` and `BaseRenderer` classes: merge everything into the `BaseHandler` class #413 
- [x] Stop splitting options into `selection` and `rendering` keys. Keep backward compatibility (with deprecation warnings). #420
- [x] Approximate feature parity between old and new handler (selection and rendering options)
- [x] Document all the changes: #429
- [x] Publish a new release of mkdocstrings
- [x] Publish a new release of mkdocstrings-python (it must depend on the new mkdocstrings version)
- [x] Publish a new release of mkdocstrings-python-legacy (it must depend on the new mkdocstrings version)
- [x] Enjoy a second round of bugtracker cleaning :drooling_face: 

---

### Phase 3

- [x] Refine griffe's ability to selectively inspect some objects (based on user configuration). **Doable with extensions**
- [x] Bring some third-party libraries support in griffe (django/pydantic/marshmallow/attrs extensions). **Extension system working** (still has some limitations but it's a good start), we have a prototype for Pydantic.
- [x] Use jinja blocks everywhere in mkdocstrings/python templates. **Blocks were added, see https://mkdocstrings.github.io/python/usage/customization/#available-blocks**

---

### Phase 4

- [ ] Add a deprecation warning in mkdocstrings/python-legacy
- [x] Progressively remove deprecated stuff. **It's been more than a year, deprecated parts in mkdocstrings are removed now** #590 

---

You are free to comment on the list items in this issue :slightly_smiling_face:

**Comment by analog-cbarber** [comment]
It would be nice if the handler could translate code references relative to the code in which it was found.

It would be nice if I could just refer to another method in the same class using just the method name,
or another top-level definition using that name. Then I could write:

    This calls the [foo][] method...

instead of

   This calls the [foo][mypackage.MyClass.foo] method...

Apart from saving typing, this would also make the raw doc string easier to read.

**Comment by pawamoy** [comment]
Could you open a feature request @analog-cbarber? That's a bit off-topic here :slightly_smiling_face:

**Comment by FasterSpeeding** [comment]
Since phase two has "Approximate feature parity between old and new handler" ticked as complete is there any rough idea of when the missed feature `inherited_members` might be implemented (even just phase wise)?

**Comment by pawamoy** [comment]
Good question! Well it will be implemented *before* the legacy handler is marked as deprecated, so in during the current phase (3). Not sure exactly when though :slightly_smiling_face: Lots of work to do these days!

**Comment by valq7711** [comment]
Hi! Could you clarify this:
I followed this https://mkdocstrings.github.io/python/usage/#global-only-options trying to include undocumented functions `(show_if_no_docstring)`, but it seems that `options` are just completely ignore :(
Only this #388 helps me (`rendering` instead of `options`). 
Tested on `py3.9.0`, fresh venv with `pip install --no-cache mkdocstrings[python]`

Thanks in advance!

**Comment by pawamoy** [comment]
Hi @valq7711, could you open a new issue please? :slightly_smiling_face:

**Comment by valq7711** [comment]
@pawamoy Done #445

**Comment by moses-kisakye** [comment]
## Mkdocstring Question

Hello am Moses, i just installed mkdocstrings to use it in my project documentation but to my suprise, when i run it in the vs code terminal, i get  the following error code message!!!
```python
moses@pythonguy:~/Desktop/11111111111/autobot$ mkdocs serve
ERROR    -  Config value 'plugins': The "mkdocstring" plugin is not installed
Aborted with 1 Configuration Errors!
```
>What could the problem be like?
- mkdocstring version* [0.19.0]

**Comment by pawamoy** [comment]
We're close to the end of the transition period.
I'll not mark yet the legacy handler as deprecated, since some projects are still using it, and have issues with the new handler. I want to fix these issues in the new handler before deprecating the legacy one.

**Comment by pawamoy** [comment]
I'll close this. The new handler is capable of everything the legacy one can do, and Griffe's extension system can be used to bring better support for specific third-party libraries. Still not marking the legacy handler as deprecated, there's no rush.
